BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Deaths" (
	"UUID"	TEXT NOT NULL,
	"Created"	TEXT NOT NULL DEFAULT current_timestamp,
	"World"	TEXT NOT NULL,
	"X"	INTEGER NOT NULL,
	"Y"	INTEGER NOT NULL,
	"Z"	INTEGER NOT NULL,
	"Inventory"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Tours" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL UNIQUE,
    "World" TEXT NOT NULL,
	"X"	INTEGER NOT NULL,
	"Y"	INTEGER NOT NULL,
	"Z"	INTEGER NOT NULL,
	"Distance" INTEGER NOT NULL,
	"IconItemStackB64" TEXT NOT NULL
);
COMMIT;
